### ISSUE TITLE
concatenate in dim 3,4 when second arg empty

### ISSUE THREAD

**Issue by ja14e6** [martinResearch/MatlabAutoDiff#13]
Hi Martin,

'cat' function throws an error when second argument is empty, i.e. cat(3, [], AutoDiff(ones(3,3))) & cat(4, [], AutoDiff(ones(3,3))) 

whereas cat(2, [], AutoDiff(ones(3,3))) & cat(4, [], ones(3,3)) works fine.

Kind regards,
James

**Comment by jh-ascham** [comment]
also occurs when inputs are flipped, i.e. cat(4, AutoDiff(ones(3,3)), [])

**Comment by martinResearch** [comment]
thank you for reporting the problem. Should be fixed now
