### ISSUE TITLE
cumsum

### ISSUE THREAD

**Issue by ja14e6** [martinResearch/MatlabAutoDiff#3]
cumsum not coded in autodiff class

**Comment by martinResearch** [comment]
Thanks for the feedback. Added cumsum with a test in last commit:
https://github.com/martinResearch/MatlabAutoDiff/commit/2e59698584556c3844503c3bde03f2654933885c
please let me now if that works for you.
Please note that the cumsum operator has a pretty dense jacobian, so forward differentiation implemented by this library might no be the right approach here and backward differentiation using another tool might be better.

**Comment by jh-ascham** [comment]
@martinResearch thank you so much. I will let you know of any others I come across.
