### ISSUE TITLE
handling zero-dimensional arrays

### ISSUE THREAD

**Issue by ja14e6** [martinResearch/MatlabAutoDiff#4]
functions such as minus cannot handle arrays having one or more dimensions of zero length

**Comment by martinResearch** [comment]
could you please provide a minimal example to reproduce ?

**Comment by jh-ascham** [comment]
`x = AutoDiff(zeros(0,1,0),zeros(0,28));
y = x - [0;0;0];`

**Comment by martinResearch** [comment]
the expression you are trying to evaluate does not seem valid even without derivatives:

```
zeros(0,1,0) - [0;0;0];
Error using  - 
Array dimensions must match for binary array op.
```

The version with derivatives does not work either which is expected.

**Comment by martinResearch** [comment]
@jamesascham , do you have a minimal example that works when not using AutodDiff and fails with it ?
