### ISSUE TITLE
diff

### ISSUE THREAD

**Issue by ja14e6** [martinResearch/MatlabAutoDiff#5]
diff not coded into autodiff class. specifically, along a third dimension.

**Comment by martinResearch** [comment]
This is fixed now , I generalized diff  to nd arrays. see 
https://github.com/martinResearch/MatlabAutoDiff/blob/05600dfb08134c55065e7001aa8deee2be2e34db/src/AutoDiff_tests.m#L83
Thanks for the feedback

**Comment by martinResearch** [comment]
@jamesascham , does that solve your problem ?
